language: swift
osx_image: xcode10.1
branches: 
  only: 
    - master
before install: 
  - gem install fastlane --no-ri --no-rdoc --no-document
install: true
script: 
  - fastlane scan -scheme TAU --device "iPhone XR"