# .github/workflows/ci.yml
name: CI

on: push

jobs:
  test:
    runs-on: macos-latest 

    env:
      FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 60

    steps:
    - uses: actions/checkout@v4

    - name: Install fastlane
      run: gem install fastlane --no-document

    - name: Run Tests with fastlane
      run: fastlane scan -s TAU --device "iPhone 16 Pro"
